// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPMVEAuwd97ZFBgMV1Lv2Dwzj2FYVwY2k',
    appId: '1:137298359155:web:2fd8733aa47992f2444b06',
    messagingSenderId: '137298359155',
    projectId: 'opensource-20200548',
    authDomain: 'opensource-20200548.firebaseapp.com',
    storageBucket: 'opensource-20200548.firebasestorage.app',
    measurementId: 'G-Z1W8LMTH58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB7YVttAQk6NgM5m2LhYkMRxvkxSKbo48',
    appId: '1:137298359155:android:39c16a2c7163901d444b06',
    messagingSenderId: '137298359155',
    projectId: 'opensource-20200548',
    storageBucket: 'opensource-20200548.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6-SmVQvoPbs0C4IqmlcMQCXHRF8HemYY',
    appId: '1:137298359155:ios:ec501c1b292b7d48444b06',
    messagingSenderId: '137298359155',
    projectId: 'opensource-20200548',
    storageBucket: 'opensource-20200548.firebasestorage.app',
    iosBundleId: 'com.example.flutterFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6-SmVQvoPbs0C4IqmlcMQCXHRF8HemYY',
    appId: '1:137298359155:ios:ec501c1b292b7d48444b06',
    messagingSenderId: '137298359155',
    projectId: 'opensource-20200548',
    storageBucket: 'opensource-20200548.firebasestorage.app',
    iosBundleId: 'com.example.flutterFb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPMVEAuwd97ZFBgMV1Lv2Dwzj2FYVwY2k',
    appId: '1:137298359155:web:53a5279092df9bba444b06',
    messagingSenderId: '137298359155',
    projectId: 'opensource-20200548',
    authDomain: 'opensource-20200548.firebaseapp.com',
    storageBucket: 'opensource-20200548.firebasestorage.app',
    measurementId: 'G-12KQPMPG3T',
  );

}