// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfbYhF4BbxE5CJImsRPQWvFMUxonogqGg',
    appId: '1:492477408603:web:914d53dbe6f938b2dde67e',
    messagingSenderId: '492477408603',
    projectId: 'flutter-lecture2-2025-xyz',
    authDomain: 'flutter-lecture2-2025-xyz.firebaseapp.com',
    storageBucket: 'flutter-lecture2-2025-xyz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4ptUmX9wtQj1umubkRXxIdESYDO2B8yI',
    appId: '1:492477408603:android:c97f9fb2e4984fb3dde67e',
    messagingSenderId: '492477408603',
    projectId: 'flutter-lecture2-2025-xyz',
    storageBucket: 'flutter-lecture2-2025-xyz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDlOtrk61FfTZLoSKWiJVNifopRrWf02g',
    appId: '1:492477408603:ios:af382ababc12c992dde67e',
    messagingSenderId: '492477408603',
    projectId: 'flutter-lecture2-2025-xyz',
    storageBucket: 'flutter-lecture2-2025-xyz.firebasestorage.app',
    iosBundleId: 'com.example.flutterFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDlOtrk61FfTZLoSKWiJVNifopRrWf02g',
    appId: '1:492477408603:ios:af382ababc12c992dde67e',
    messagingSenderId: '492477408603',
    projectId: 'flutter-lecture2-2025-xyz',
    storageBucket: 'flutter-lecture2-2025-xyz.firebasestorage.app',
    iosBundleId: 'com.example.flutterFb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfbYhF4BbxE5CJImsRPQWvFMUxonogqGg',
    appId: '1:492477408603:web:e027c4702035faf9dde67e',
    messagingSenderId: '492477408603',
    projectId: 'flutter-lecture2-2025-xyz',
    authDomain: 'flutter-lecture2-2025-xyz.firebaseapp.com',
    storageBucket: 'flutter-lecture2-2025-xyz.firebasestorage.app',
  );
}
