// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbEPzHuG2kKPiR5q00pzBCBlVhGnFyUm0',
    appId: '1:800134555306:web:4b63a0231f4d2f3e1312d3',
    messagingSenderId: '800134555306',
    projectId: 'opensource-teamproject',
    authDomain: 'opensource-teamproject.firebaseapp.com',
    storageBucket: 'opensource-teamproject.firebasestorage.app',
    measurementId: 'G-6K6LJPRKEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCbHgLyqhluTcv8hqSfihYAUIJQG0jUs8',
    appId: '1:800134555306:android:cff86eccaaa7bf941312d3',
    messagingSenderId: '800134555306',
    projectId: 'opensource-teamproject',
    storageBucket: 'opensource-teamproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwdezuw9O11iElI_G4sGdjLgjXsaPiVkc',
    appId: '1:800134555306:ios:09df3542f9a3912b1312d3',
    messagingSenderId: '800134555306',
    projectId: 'opensource-teamproject',
    storageBucket: 'opensource-teamproject.firebasestorage.app',
    iosBundleId: 'com.example.flutterFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwdezuw9O11iElI_G4sGdjLgjXsaPiVkc',
    appId: '1:800134555306:ios:09df3542f9a3912b1312d3',
    messagingSenderId: '800134555306',
    projectId: 'opensource-teamproject',
    storageBucket: 'opensource-teamproject.firebasestorage.app',
    iosBundleId: 'com.example.flutterFb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbEPzHuG2kKPiR5q00pzBCBlVhGnFyUm0',
    appId: '1:800134555306:web:f9efdc3697732d641312d3',
    messagingSenderId: '800134555306',
    projectId: 'opensource-teamproject',
    authDomain: 'opensource-teamproject.firebaseapp.com',
    storageBucket: 'opensource-teamproject.firebasestorage.app',
    measurementId: 'G-TQ6VSQ75MH',
  );
}
